version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./insofad_frontend
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"

  backend:
    container_name: api
    build:
      context: ./insofad_backend
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/luxuryproductsbob
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luxuryproductsbob
    ports:
      - "5432:5432"
